- name: postfix installed
  apt:
    pkg: postfix
    state: installed

- name: postfix configured to listen only on loopback interface
  lineinfile:
    line: "inet_interfaces = loopback-only"
    regexp: "^inet_interfaces ="
    dest: /etc/postfix/main.cf
  notify: Restart postfix

- name: Remove existing relayhost line
  lineinfile:
    regexp: "^relayhost = $"
    dest: /etc/postfix/main.cf
    state: absent
  when: {{ debian_mailout_use_smarthost }}
  notify: Restart postfix

- name: relayhost
  blockinfile:
    block: |
      smtp_sasl_auth_enable =  yes
      smtp_tls_security_level = encrypt
      smtp_sasl_tls_security_options = noanonymous
      relayhost = [{{ debian_mailout_smarthost_hostname }}]:{{ debian_mailout_smarthost_port }}
      smtp_sasl_password_maps =  hash:/etc/postfix/relay_passwd
    dest: /etc/postfix/main.cf
  when: {{ debian_mailout_use_smarthost }}
  notify: Restart postfix

- name: relay_passwd
  template:
    src: relay_passwd.j2
    dest: /etc/postfix/relay_passwd
    mode: 0600
    owner: root
    group: root
  notify:
  - postmap relay_passwd
  - Restart postfix
  when: {{ debian_mailout_use_smarthost }}

- name: mydestination
  lineinfile:
    line: "mydestination = localhost {{ inventory_hostname }} {{ inventory_hostname_short }}"
    regexp: "^mydestination ="
    dest: /etc/postfix/main.cf
  notify: Restart postfix
